name: Ciao

on:
  push:
  pull_request:
    types: [opened]

jobs:
  come:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo ${{github.action_repository}}
          echo ${{github.actor}}
          echo ${{github.event}}
          echo ${{github.repository}}
          echo ${{github.repository_owner}}
          echo ${{github.workflow_ref}}
      - name: secret
        run: |
          echo ${{secrets.BANANA}}
          echo ${{secrets.BANANA}}
